# Generated by Django 5.2.3 on 2025-07-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_patient_case_supervisor_patient_final_therapist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="pre_assessment_therapist",
        ),
    ]
